# Generated by Django 3.2.8 on 2021-10-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('school', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('famsize', models.CharField(max_length=255)),
                ('Pstatus', models.CharField(max_length=255)),
                ('Medu', models.IntegerField()),
                ('Fedu', models.IntegerField()),
                ('Mjob', models.CharField(max_length=255)),
                ('Fjob', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('guardian', models.CharField(max_length=255)),
                ('traveltime', models.IntegerField()),
                ('studytime', models.IntegerField()),
                ('failures', models.IntegerField()),
                ('schoolsup', models.CharField(max_length=255)),
                ('famsup', models.CharField(max_length=255)),
                ('paid', models.CharField(max_length=255)),
                ('activities', models.CharField(max_length=255)),
                ('nursery', models.CharField(max_length=255)),
                ('higher', models.CharField(max_length=255)),
                ('internet', models.CharField(max_length=255)),
                ('romantic', models.CharField(max_length=255)),
                ('famrel', models.IntegerField()),
                ('freetime', models.IntegerField()),
                ('goout', models.IntegerField()),
                ('Dalc', models.IntegerField()),
                ('Walc', models.IntegerField()),
                ('health', models.IntegerField()),
                ('absences', models.IntegerField()),
                ('G1', models.IntegerField()),
                ('G2', models.IntegerField()),
                ('G3', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
