# Generated by Django 3.2.8 on 2021-10-29 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passpredictor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfos',
            name='step',
        ),
    ]
